/**
 * Setup Environment Script
 * Создает .env файл для backend с базовыми настройками для development
 */

import { writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const envPath = join(__dirname, '.env');

// Проверяем, существует ли уже .env
if (existsSync(envPath)) {
  console.log('⚠️  .env файл уже существует!');
  console.log('   Если хотите пересоздать, удалите старый файл и запустите скрипт снова.');
  process.exit(0);
}

// Содержимое .env для development
const envContent = `# Brix Nutritional App - Backend Environment Variables
# DEVELOPMENT MODE - Auto-generated by setup-env.js

# ======================
# Server
# ======================
NODE_ENV=development
HOST=0.0.0.0
PORT=3000
LOG_LEVEL=info

# ======================
# Database (PostgreSQL from Docker)
# ======================
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=brix_nutrition
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=postgres
DATABASE_SSL=false

# ======================
# Redis (from Docker)
# ======================
REDIS_HOST=localhost
REDIS_PORT=6379

# ======================
# JWT Secrets (DEVELOPMENT ONLY!)
# ⚠️  IMPORTANT: Generate new secrets for production!
# ======================
JWT_SECRET=dev-jwt-secret-${Date.now()}-replace-in-production
API_TOKEN_SALT=dev-api-token-salt-${Date.now()}
ADMIN_JWT_SECRET=dev-admin-jwt-secret-${Date.now()}

# ======================
# OpenAI (AI Консультант) - OPTIONAL
# ======================
# Раскомментируйте и добавьте ваш ключ:
# OPENAI_API_KEY=sk-your-openai-api-key-here
OPENAI_MODEL=gpt-4
OPENAI_MAX_TOKENS=1000

# ======================
# Twilio (SMS) - OPTIONAL
# ======================
# Раскомментируйте когда будете тестировать SMS:
# TWILIO_ACCOUNT_SID=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# TWILIO_AUTH_TOKEN=your-twilio-auth-token
# TWILIO_PHONE_NUMBER=+1234567890

# ======================
# Stripe (Платежи) - OPTIONAL
# ======================
# STRIPE_SECRET_KEY=sk_test_your-stripe-secret-key
# STRIPE_WEBHOOK_SECRET=whsec_your-stripe-webhook-secret

# ======================
# AWS S3 (Медиа) - OPTIONAL
# ======================
# AWS_ACCESS_KEY_ID=your-aws-access-key-id
# AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key
# AWS_REGION=us-east-1
# AWS_S3_BUCKET=brix-nutrition

# ======================
# Email (SMTP) - Using Mailhog from Docker
# ======================
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USER=
SMTP_PASS=
USE_MOCK_EMAIL=true

# ======================
# Frontend URL (для CORS)
# ======================
FRONTEND_URL=http://localhost:3000

# ======================
# Rate Limiting
# ======================
RATE_LIMIT_MAX=100
RATE_LIMIT_WINDOW_MS=60000
`;

try {
  writeFileSync(envPath, envContent);
  console.log('✅ .env файл успешно создан!');
  console.log('📝 Путь:', envPath);
  console.log('');
  console.log('🔧 Настройки по умолчанию:');
  console.log('   - PostgreSQL: localhost:5432 (запустится через Docker)');
  console.log('   - Redis: localhost:6379 (запустится через Docker)');
  console.log('   - Backend: http://0.0.0.0:3000');
  console.log('');
  console.log('⚠️  ВАЖНО:');
  console.log('   - JWT секреты используют временные значения для dev');
  console.log('   - OpenAI, Twilio, Stripe закомментированы (добавьте позже)');
  console.log('   - Для production ОБЯЗАТЕЛЬНО замените все секреты!');
  console.log('');
  console.log('➡️  Следующий шаг: запустите Docker контейнеры');
  console.log('   docker-compose up -d');
} catch (error) {
  console.error('❌ Ошибка создания .env:', error.message);
  process.exit(1);
}
